### **1.Create Numpy Arrays**

In [170]:
#List of libraries used:
#Importing numpy library
import numpy as np

In [106]:
#1.1.Create an array
np.array([1,2,3])

array([1, 2, 3])

In [107]:
#1.2.Let x = [1, 2]. Convert it into an array.
x=[1,2]
np.array(x)

array([1, 2])

In [108]:
#1.3.Create an 2D array with shape of (3,2), filled with ones.
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [109]:
#1.4.Create a 3x3 2D array with ones on the diagonal and zeros elsewhere. 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [110]:
#1.5.Create an 2D array of 2 x 5 shape, filled with 6.
np.full((2,5),6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [111]:
#1.6.Create an array of 2, 4, 6, 8, ..., 98, 100.
np.arange(2,102,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [112]:
#1.7.1.Create an array of 10 zeros
np.full((10,),0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [113]:
#1.7.2.Create an array of 10 fives
np.full((10,),5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [114]:
#1.8.Create an 3x3x3 array filled with arbitrary values.
np.random.seed(0)
np.random.randint(100,size=(3,3,3))

array([[[44, 47, 64],
        [67, 67,  9],
        [83, 21, 36]],

       [[87, 70, 88],
        [88, 12, 58],
        [65, 39, 87]],

       [[46, 88, 81],
        [37, 25, 77],
        [72,  9, 20]]])

In [115]:
#1.9.Create a 3x4 2D array filled with values from 10 to 21 (inclusive).
np.random.randint(10,22,size=(3,4))

array([[13, 10, 13, 15],
       [10, 12, 13, 18],
       [11, 13, 13, 13]])

In [116]:
#1.10.Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers
a=np.arange(5,50,3)
a1=a[:10]
a1

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

### **2.Operations on Numpy Arrays**

In [174]:
#2.1.Create an array of shape (3, 2) and populate it with random samples from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.
np.random.seed(100)
op1=np.random.uniform(0,1,size=(3,2))
op1

array([[0.54340494, 0.27836939],
       [0.42451759, 0.84477613],
       [0.00471886, 0.12156912]])

In [175]:
#2.2.Find the index of 5th repetition of number 1 in the given array x.
x=[1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
x=np.array(x)
count=0
for i in range(len(x)):
    if x[i]==1:
        count=count+1
        if count==5:
            print(i)

8


In [118]:
#2.3.Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.
x=np.arange(1,10)
x1=x[:4]
x2=x[5:8]
x3=x[-2:]
print(x1,x2,x3)

[1 2 3 4] [6 7 8] [8 9]


In [119]:
#2.4.Use np.split to split the array into left and right halves.
x4=  [[ 0., 1., 2., 3.], [ 4., 5., 6., 7.], [ 8., 9., 10., 11.], [ 12., 13., 14., 15.]]
np.split(x4,[2])

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

In [120]:
#2.5.1.Slicing to get the sub-array [[10,15], [25,30]]
x5=[[5,10,15], [20,25,30], [35,40,45]]
x5=np.array(x5)
x5[:2,1:]

array([[10, 15],
       [25, 30]])

In [121]:
#2.5.2. Getting individual element value "20"
x5[1:2,:1]

array([[20]])

In [122]:
#2.6.Concatenate x and y
x=np.array([[ 1, 2, 3], [ 4, 5, 6]])
y=np.array([[ 7, 8, 9], [10, 11 ,12]])
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [123]:
#2.7.Compute the min/max (min is divided by max) for each row for given 2d numpy array, in which integer values range from 1 to 10 and shape is (5,3).
np.random.seed(100)
x=np.random.randint(10,size=(5,3))
num_row,num_col=x.shape
for i in range(num_row):
    curr_min=x[i,0]
    for j in range(num_col):
        if curr_min>x[i,j]:
            curr_max=curr_min
            curr_min=x[i,j]
        else:
            curr_max=x[i,j]
        if j==num_col-1:
            div=curr_min/curr_max
            print("\n",div)


 0.375

 0.0

 0.4

 1.0

 0.0


In [144]:
#2.8.Convert 3 arrays into a flat linear 1d array
arr1=np.arange(0,3,1)
arr2=np.arange(3,7,1)
arr3=np.arange(7,10,1)
np.concatenate((arr1,arr2,arr3),axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [125]:
#2.9.Get all items between 5 and 10 from a.
a=np.array([2, 6, 1, 9, 10, 3, 27])
for i in range(len(a)):
    if a[i]>5 and a[i]<10:
        print(a[i])

6
9


In [126]:
#2.10.Get the positions where elements of a and b match.
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array( [7,2,10,2,7,4,9,4,9,8])
for i in range(len(a)):
    for j in range(len(b)):
        if a[i]==b[j]:
            print("The value",a[i],"at position: a=",i,"& at b=",j,"\n")

The value 2 at position: a= 1 & at b= 1 

The value 2 at position: a= 1 & at b= 3 

The value 2 at position: a= 3 & at b= 1 

The value 2 at position: a= 3 & at b= 3 

The value 4 at position: a= 5 & at b= 5 

The value 4 at position: a= 5 & at b= 7 

The value 4 at position: a= 7 & at b= 5 

The value 4 at position: a= 7 & at b= 7 



In [127]:
#2.11.Replace all odd numbers in arr with -1 without changing arr:
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
for i in range(len(arr)):
    if arr[i]%2!=0:
        arr[i]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [145]:
#2.12.Stack the arrays a and then b horizontally in order.
np.random.seed(100)
a=np.random.randint(0,10,size=(2,5))
b=np.ones((2,5),dtype=int)
np.stack((a,b))

array([[[8, 8, 3, 7, 7],
        [0, 4, 2, 5, 2]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

###  **3.Indexing and Slicing** 

In [181]:
#3.1.1.To get all elements except the first
#3.1.2.To get all elements except the last
#3.1.3.To get every other element of the array (operation from the first element)
#3.1.4. To get every element of the array except the first element
#3.1.5.To reverse the array
a=np.array( [ 3, 6, 9, 25, 10, 8] )
print("The arrya a:",a,"\n")
print("All elements except first:",a[1:],"\n")
print("To get all elements except the last:",a[:-1],"\n")
print("To get every other element from first element:",a[::2],"\n")
print(" To get every element of the array except the first element:",a[1::2],"\n")
print("Reverse of the array:",np.flip(a),"\n")

The arrya a: [ 3  6  9 25 10  8] 

All elements except first: [ 6  9 25 10  8] 

To get all elements except the last: [ 3  6  9 25 10] 

To get every other element from first element: [ 3  9 10] 

 To get every element of the array except the first element: [ 6 25  8] 

Reverse of the array: [ 8 10 25  9  6  3] 



In [159]:
#3.2.1.Create an array with the components as 0-31 and the shape is (8,4).
b=np.arange(32).reshape(8,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [131]:
#3.2.2.Set the 3rd element in the 1st row to 0.
b[0,2]=0
b

array([[ 0,  1,  0,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [132]:
b[:,1:2]

array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21],
       [25],
       [29]])

In [133]:
#3.2.3.the second column.
b[:1,:1]

array([[0]])

In [160]:
#3.2.4.Get the 3x3 region from the array: 
b[2:5,1:]

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [135]:
#3.3.Create an 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal. Please use the numpy "slicing" method to realize. 
stagg= np.zeros((4, 4))
stagg[::2, 1::2] = 1
stagg[1::2, ::2] = 1
stagg

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [161]:
#3.4.Subtract the 1d array b_1d from the 2d array a_2d, such that each item of b_1d subtracts from respective row of a_2d.
a_2d =np.array( [[3,3,3],[4,4,4],[5,5,5]])
b_1d=np.array([1,1,1])
desired_arr=np.empty(np.shape(a_2d))
for i in range(len(a_2d)):
    for j in range(len(a_2d)):
       desired_arr[i,j]=a_2d[i,j]-b_1d[i]
desired_arr

array([[2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

###  **4. Average, variance, standard deviation of the 1000 elements array** 

In [137]:
np.random.seed(100)
main_arr=np.random.randint(100,size=(1000,))
main_arr
print("The average of the matrix is:",np.around(np.average(main_arr),decimals=5))
print("The Variance of the matrix is:",np.around(np.var(main_arr),decimals=5))
print("The Standard Deviation of the matrix is:",np.around(np.std(main_arr),decimals=5))

The average of the matrix is: 50.377
The Variance of the matrix is: 834.04687
The Standard Deviation of the matrix is: 28.87987


### **5.Write a 6x6 times table matrix**

In [138]:
#5.1.By using numpy broadcasting
num_a=np.arange(1,7,dtype=int)
num_b=np.vstack(num_a)
table_arr=num_a*num_b
table_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [139]:
#5.2.By using for loop
table_arr=np.empty([6,6],dtype=int)
for i in range(len(num_a)):
    for j in range(len(num_a)):
        table_arr[i,j]=num_a[i]*num_a[j]
table_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

### **6.Broadcasting in Practice: Centering an array**

In [165]:
#6.1.Imagine you have an array of 10 observations, each of which consists of 3 values(floating-point numbers). Store this in an array with the shape(10, 3). Seed is set as 100. 
#6.2.Compute the mean of each feature using the mean aggregate across the first dimension:
np.random.seed(100)
observ_val=np.random.randint(100,size=(10,3)).astype("float")
observ_ave=np.mean(observ_val,axis=0)
print("The array of observed value:",observ_val)
print("\n The array of observed  mean value:",observ_ave)

The array of observed value: [[ 8. 24. 67.]
 [87. 79. 48.]
 [10. 94. 52.]
 [98. 53. 66.]
 [98. 14. 34.]
 [24. 15. 60.]
 [58. 16.  9.]
 [93. 86.  2.]
 [27.  4. 31.]
 [ 1. 13. 83.]]

 The array of observed  mean value: [50.4 39.8 45.2]


In [141]:
#6.3.Center the X array by subtracting the mean:
center_val=observ_val-observ_ave
center_val

array([[-42.4, -15.8,  21.8],
       [ 36.6,  39.2,   2.8],
       [-40.4,  54.2,   6.8],
       [ 47.6,  13.2,  20.8],
       [ 47.6, -25.8, -11.2],
       [-26.4, -24.8,  14.8],
       [  7.6, -23.8, -36.2],
       [ 42.6,  46.2, -43.2],
       [-23.4, -35.8, -14.2],
       [-49.4, -26.8,  37.8]])

In [142]:
#6.4.Double-check the correctness of the centralization using the mean aggregate again (check that the centered array has near zero mean).
np.mean(center_val,axis=0)

array([ 1.42108547e-15,  2.84217094e-15, -2.84217094e-15])